server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://44.200.201.232:3307/student
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update