spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://44.200.201.232:3307/customer
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
